version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - aws --version

  pre_build:
    commands:
      - echo "Validating CloudFormation templates..."
      - |
        for template in templates/*.yaml; do
          echo "Validating $template..."
          aws cloudformation validate-template --template-body file://$template
        done

  build:
    commands:
      - echo "All templates validated successfully."

  post_build:
    commands:
      - echo "Packaging templates into output directory..."
      - mkdir -p output/templates
      - cp templates/*.yaml output/templates/
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
