version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install cfn-lint boto3 awscli

  pre_build:
    commands:
      - echo "Starting CloudFormation Linting..."
      - cfn-lint templates/*.yaml || true
      - echo "CloudFormation template linting complete."

  build:
    commands:
      - echo "Validating templates with AWS CloudFormation..."
      # Validate each template before deployment
      - for template in templates/*.yaml; do
          echo "Validating $template";
          aws cloudformation validate-template --template-body file://$template || exit 1;
        done
      - echo "Build stage completed successfully."

  post_build:
    commands:
      - echo "Preparing artifacts for deployment..."
      - echo "All validations completed successfully."

artifacts:
  files:
    - templates/*.yaml
  discard-paths: yes

