version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install cfn-lint boto3 awscli

  pre_build:
    commands:
      - echo "Running CloudFormation Lint..."
      - cfn-lint templates/*.yaml || true
      - echo "Linting complete."

  build:
    commands:
      - echo "Validating CloudFormation templates..."
      - for template in templates/*.yaml; do
          echo "Validating $template";
          aws cloudformation validate-template --template-body file://$template || exit 1;
        done
      - echo "Template validation complete."

  post_build:
    commands:
      - echo "All validations completed successfully."
      - echo "Ready for deployment."

artifacts:
  files:
    - templates/*.yaml
  discard-paths: yes
