version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - aws --version

  pre_build:
    commands:
      - echo "Validating CloudFormation templates..."
      - |
        for template in templates/*.yaml; do
          echo "Validating $template..."
          aws cloudformation validate-template --template-body file://$template
        done

  build:
    commands:
      - echo "Packaging application files..."
      - mkdir -p output/templates
      - mkdir -p output/app
      - cp templates/*.yaml output/templates/
      - cp app/index.template.html output/app/index.html
      - echo "Build stage complete."

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
