AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Multi-region CI/CD Pipeline for 3-tier CloudFormation app
  (Dev in us-east-1, Prod in us-west-2)

Parameters:
  GitHubOwner:
    Type: String
    Default: anzy-anzy

  GitHubRepo:
    Type: String
    Default: cicd-3tier-cloudformation

  GitHubBranch:
    Type: String
    Default: main

  GitHubToken:
    Type: String
    NoEcho: true

  ProjectName:
    Type: String
    Default: cicd-pipeline-stack

  ArtifactBucketEastName:
    Type: String
    Default: ""
    Description: "Existing S3 bucket in us-east-1 for artifacts"

  ArtifactBucketWestName:
    Type: String
    Default: ""
    Description: "Existing S3 bucket in us-west-2 for artifacts"

Conditions:
  CreateEastBucket: !Equals [!Ref ArtifactBucketEastName, ""]
  CreateWestBucket: !Equals [!Ref ArtifactBucketWestName, ""]

Resources:

  ArtifactBucketEast:
    Type: AWS::S3::Bucket
    Condition: CreateEastBucket

  ArtifactBucketWest:
    Type: AWS::S3::Bucket
    Condition: CreateWestBucket

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-CodePipelineRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - cloudformation:*
                  - iam:PassRole
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                  - ec2:Describe*
                Resource: "*"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                  - cloudformation:ValidateTemplate
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectName}-multi-region-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn

      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !If
              - CreateEastBucket
              - !Ref ArtifactBucketEast
              - !Ref ArtifactBucketEastName

        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: !If
              - CreateWestBucket
              - !Ref ArtifactBucketWest
              - !Ref ArtifactBucketWestName

      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts: [ { Name: SourceArtifact } ]
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts: [ { Name: SourceArtifact } ]
              OutputArtifacts: [ { Name: BuildArtifact } ]
              Configuration:
                ProjectName: !Ref CodeBuildProject

        - Name: DeployDev
          Actions:
            - Name: DeployAppDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Region: us-east-1
              InputArtifacts: [ { Name: BuildArtifact } ]
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: app-stack-dev
                RoleArn: !GetAtt CodePipelineRole.Arn
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub '{"EnvName": "DEV", "ArtifactBucket": "${ArtifactBucketEastName}"}'
              RunOrder: 1

            - Name: DeployDBDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Region: us-east-1
              InputArtifacts: [ { Name: BuildArtifact } ]
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: db-stack-dev
                RoleArn: !GetAtt CodePipelineRole.Arn
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: '{"EnvName":"DEV"}'
              RunOrder: 2

        - Name: ManualApproval
          Actions:
            - Name: ApproveForProd
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1

        - Name: DeployProd
          Actions:
            - Name: DeployAppProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Region: us-west-2
              InputArtifacts: [ { Name: BuildArtifact } ]
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: app-stack-prod
                RoleArn: !GetAtt CodePipelineRole.Arn
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub '{"EnvName": "PROD", "ArtifactBucket": "${ArtifactBucketWestName}"}'
              RunOrder: 1

            - Name: DeployDBProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Region: us-west-2
              InputArtifacts: [ { Name: BuildArtifact } ]
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: db-stack-prod
                RoleArn: !GetAtt CodePipelineRole.Arn
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: '{"EnvName":"PROD"}'
              RunOrder: 2

Outputs:
  PipelineName:
    Description: Pipeline name
    Value: !Ref CICDPipeline
