AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EC2 Application Stack for 3-tier CI/CD Project.
  Launches EC2 instances in public subnets, connects to RDS, and uses security groups.

Parameters:
  EnvName:
    Type: String
    Default: DEV
    Description: Environment name (e.g., DEV, TEST, PROD)

  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type for the app servers

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mykeypair
    Description: EC2 Key Pair name for SSH access

  AmiId:
    Type: AWS::EC2::Image::Id
    Default: ami-04f9aa2b7c7091927
    Description: Amazon Linux 2 AMI (update if needed for your region)

  # -------------------------------------------
  # NEW: Dummy parameter to force stack updates
  # -------------------------------------------
  ForceUpdate:
    Type: String
    Default: "1"
    Description: Forces CloudFormation to detect updates

Resources:
  # --------------------------------------------------------
  # Security Group for EC2 Instances
  # --------------------------------------------------------
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !ImportValue
        Fn::Sub: "${EnvName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-AppSecurityGroup"

  # --------------------------------------------------------
  # EC2 Instance for Application Tier
  # --------------------------------------------------------
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SubnetId: !Select
        - 0
        - !Split
          - ","
          - !ImportValue
              Fn::Sub: "${EnvName}-PublicSubnets"
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-AppServer"
        - Key: ForceUpdate
          Value: !Ref ForceUpdate   # <-- ensures instance always updates

Outputs:
  AppInstanceId:
    Description: EC2 Instance ID
    Value: !Ref AppInstance
    Export:
      Name: !Sub "${EnvName}-AppInstanceId"

  AppSecurityGroupId:
    Description: Security Group ID for App Server
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub "${EnvName}-AppSecurityGroupId"

  PublicSubnetUsed:
    Description: The subnet where EC2 was launched
    Value: !Select
      - 0
      - !Split
        - ","
        - !ImportValue
            Fn::Sub: "${EnvName}-PublicSubnets"
