AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EC2 Application Stack for 3-tier CI/CD Project.
  Launches EC2 instances in public subnets, connects to RDS, and uses security groups.

Parameters:
  EnvName:
    Type: String
    Default: DEV
    Description: Environment name (e.g., DEV, TEST, PROD)

  InstanceType:
    Type: String
    Default: t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mykeypair

  AmiId:
    Type: String
    Default: ""
    Description: "Leave empty — automatic AMI mapping will select correct AMI"

  ForceUpdate:
    Type: String
    Default: "1"

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-06dd5c911c0d8dcdc
    us-west-2:
      AMI: ami-04f9aa2b7c7091927

Conditions:
  UseProvidedAmi: !Not [!Equals [!Ref AmiId, ""]]

Resources:

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !ImportValue
        Fn::Sub: "${EnvName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-AppSecurityGroup"

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !If
        - UseProvidedAmi
        - !Ref AmiId
        - !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyName
      SubnetId: !Select
        - 0
        - !Split
          - ","
          - !ImportValue
              Fn::Sub: "${EnvName}-PublicSubnets"
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-AppServer"
        - Key: ForceUpdate
          Value: !Ref ForceUpdate

Outputs:
  AppInstanceId:
    Value: !Ref AppInstance
    Export:
      Name: !Sub "${EnvName}-AppInstanceId"

  AppSecurityGroupId:
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub "${EnvName}-AppSecurityGroupId"

  PublicSubnetUsed:
    Value: !Select
      - 0
      - !Split
        - ","
        - !ImportValue
            Fn::Sub: "${EnvName}-PublicSubnets"
